### ISSUE TITLE
Use imap instead of hosting a mail server.

### ISSUE THREAD

**Issue by jtagcat** [leafac/kill-the-newsletter.com#26]
I already have a mail server, keep it simple.

**Comment by leafac** [comment]
You may be interested in [this implementation](https://github.com/leafac/kill-the-newsletter.com/tree/sinatra). I no longer use or support it, but it’s closer to what you want: it does use a separate mail server but not IMAP. I, for one, found it simpler to have the application be a mail server instead of configuring a separate mail server. To each its own…
