### ISSUE TITLE
I would appreciate it if you could support easy installation.

### ISSUE THREAD

**Issue by eyoungmin** [leafac/kill-the-newsletter.com#28]
I appreciate this service. I don't like to read newsletters in email. Also, I would like to share newsletters with my team members and other partners. This is a great service. I mainly use slack, discord, telegram. A lot of newsletters keep coming up. It's a flow. I read a lot of newsletters to get insight.

This has no limit on quantity compared to similar services. 
However, I am worried that my behavior will put pressure on the server. It would be nice if I could selfhost with Heroku or Vercel. Can you help me?

**Comment by leafac** [comment]
Follow the instructions here: https://github.com/leafac/kill-the-newsletter.com#deploy-your-own-instance-self-host

You can’t deploy to Heroku or Vercel because **Kill the Newsletter!** needs access to a filesystem that isn’t ephemeral (in Heroku and Vercel your filesystem is wiped out from time to time). But DigitalOcean works fine.
