### ISSUE TITLE
URL redirection resolver

### ISSUE THREAD

**Issue by mlthlschr** [leafac/kill-the-newsletter.com#36]
I wonder if it would be possible to have an URL redirection resolver. Some of the newsletters I subscribed to are doing heavy tracking with marketing URLS, such as https://click.convertkit-mail4.com/38u6[...]0ap/l2he[...]d5f6/aHR0[...]MTI5

If the server would resolve the link to its final destination, the tracking would at least be delegated to the server side and thus be more private for the user. Don't know whether this would imply other security-related problems with this approach, though.

**Comment by jtagcat** [comment]
There's risk that you end up with a broken link, so the original should be available (untampered version).
You also most likely have to run JS and stuff. It would be quite complex…

With this FR, I'd say public newsletters would be nice. (As in, one person subscribes, others can take the RSS feed right away). Though, this has the risk of a jerk unsubscribing as everyone.

**Comment by leafac** [comment]
Thanks for the suggestion. My initial reaction is to not add the feature you mentioned. I dislike tracking and would like to avoid it as much as you do, but here are my reasons against the feature:

1. Up to now we never tried to alter or process the contents of the newsletter in any way, and I think it’s best to continue with that approach. **Kill the Newsletter!** should only repackage emails into feeds as transparently as possible. There’s too much that could break and things could get too complex. 

2. I don’t think **Kill the Newsletter!** is the right place to try and prevent tracking. There are browsers specifically made for this, TOR, VPNs, and so forth. If you use them, then you really solve the problem, not only for newsletters. 

Regarding public newsletters, I think they are a bad idea for the reason you mentioned: anyone can click on the unsubscribe link, sign up for other stuff, or just plain out send you spam. Also, I had angry publishers contact me before complaining that the service was ripping off their content, so public newsletters is a line I don’t want to cross (this is another good reason to keep the content intact instead of changing links). 

All that said, if you send a Pull Request I’ll consider it.

I’m closing this for now, but thanks for your contribution and for the conversation. I hope you continue enjoying the service. And that you support its development: https://patreon.com/leafac https://paypal.me/LeandroFacchinetti
